language: objective-c
before_install:
  - gem install xcpretty
script:
  - rake "clean['TwitterClient-iOS RichTextEditor TwitterClient-Mac']"
  - rake "build['TwitterClient-iOS RichTextEditor TwitterClient-Mac']"
   