language: objective-c
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
install:
  - bundle install --path=vendor/bundle --binstubs=vendor/bin
script:
  - bundle exec rake
branches:
  only:
    - master
